---

- hosts: atlassian
  tasks:
    - set_fact:
        atlassian_url: "{{ atlassian.url }}" 
      when: 
        - atlassian is defined
        - atlassian.url is defined
    - set_fact:
        atlassian_url: "{{ global_config.atlassian.url }}" 
      when: 
        - atlassian is undefined
        - atlassian.url is undefined
    - debug:
        msg: "hello {{ atlassian_url }}"
